version: "{build}"
environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.11"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
build: OFF
platform:
  - x86
configuration:
  - Release
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version
  - npm --version
  - npm install gulp -g
  - npm install
test_script:
  - gulp