version: "{build}"
environment:
  matrix:
    - nodejs_version: 0.10
build: OFF
platform:
  - x86
configuration:
  - Release
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:Platform
  - node --version
  - npm --version
  - npm install gulp -g
  - npm install
test_script:
  - gulp